services:
  - type: web
    name: movie-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OMDB_API_KEY
        sync: false  
      - key: KINOPOISK_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RENDER_EXTERNAL_URL  # Добавьте эту переменную!
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
